// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyletter.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyStatus int32

const (
	VerifyStatus_FAILED  VerifyStatus = 0
	VerifyStatus_SUCCESS VerifyStatus = 1
)

var VerifyStatus_name = map[int32]string{
	0: "FAILED",
	1: "SUCCESS",
}

var VerifyStatus_value = map[string]int32{
	"FAILED":  0,
	"SUCCESS": 1,
}

func (x VerifyStatus) String() string {
	return proto.EnumName(VerifyStatus_name, int32(x))
}

func (VerifyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{0}
}

type FailedReason int32

const (
	FailedReason_NONE             FailedReason = 0
	FailedReason_AUTH_FAILED      FailedReason = 1
	FailedReason_INTERNAL_ERR     FailedReason = 2
	FailedReason_REJECT_HOST      FailedReason = 3
	FailedReason_NO_HOST_WAITED   FailedReason = 4
	FailedReason_RESPONSE_TIMEOUT FailedReason = 5
)

var FailedReason_name = map[int32]string{
	0: "NONE",
	1: "AUTH_FAILED",
	2: "INTERNAL_ERR",
	3: "REJECT_HOST",
	4: "NO_HOST_WAITED",
	5: "RESPONSE_TIMEOUT",
}

var FailedReason_value = map[string]int32{
	"NONE":             0,
	"AUTH_FAILED":      1,
	"INTERNAL_ERR":     2,
	"REJECT_HOST":      3,
	"NO_HOST_WAITED":   4,
	"RESPONSE_TIMEOUT": 5,
}

func (x FailedReason) String() string {
	return proto.EnumName(FailedReason_name, int32(x))
}

func (FailedReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{1}
}

type Key struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Code struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{1}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GuestInfo struct {
	Ua                   string   `protobuf:"bytes,1,opt,name=ua,proto3" json:"ua,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestInfo) Reset()         { *m = GuestInfo{} }
func (m *GuestInfo) String() string { return proto.CompactTextString(m) }
func (*GuestInfo) ProtoMessage()    {}
func (*GuestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{2}
}

func (m *GuestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestInfo.Unmarshal(m, b)
}
func (m *GuestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestInfo.Marshal(b, m, deterministic)
}
func (m *GuestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestInfo.Merge(m, src)
}
func (m *GuestInfo) XXX_Size() int {
	return xxx_messageInfo_GuestInfo.Size(m)
}
func (m *GuestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GuestInfo proto.InternalMessageInfo

func (m *GuestInfo) GetUa() string {
	if m != nil {
		return m.Ua
	}
	return ""
}

func (m *GuestInfo) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type VerifyRequest struct {
	GuestInfo            *GuestInfo `protobuf:"bytes,1,opt,name=guestInfo,proto3" json:"guestInfo,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{3}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetGuestInfo() *GuestInfo {
	if m != nil {
		return m.GuestInfo
	}
	return nil
}

func (m *VerifyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyReply struct {
	Status               VerifyStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dev.namhyun.keyletter.VerifyStatus" json:"status,omitempty"`
	Reason               FailedReason `protobuf:"varint,2,opt,name=reason,proto3,enum=dev.namhyun.keyletter.FailedReason" json:"reason,omitempty"`
	Key                  string       `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyReply) Reset()         { *m = VerifyReply{} }
func (m *VerifyReply) String() string { return proto.CompactTextString(m) }
func (*VerifyReply) ProtoMessage()    {}
func (*VerifyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{4}
}

func (m *VerifyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReply.Unmarshal(m, b)
}
func (m *VerifyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReply.Marshal(b, m, deterministic)
}
func (m *VerifyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReply.Merge(m, src)
}
func (m *VerifyReply) XXX_Size() int {
	return xxx_messageInfo_VerifyReply.Size(m)
}
func (m *VerifyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReply proto.InternalMessageInfo

func (m *VerifyReply) GetStatus() VerifyStatus {
	if m != nil {
		return m.Status
	}
	return VerifyStatus_FAILED
}

func (m *VerifyReply) GetReason() FailedReason {
	if m != nil {
		return m.Reason
	}
	return FailedReason_NONE
}

func (m *VerifyReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type WaitPermitRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Permit               bool     `protobuf:"varint,2,opt,name=permit,proto3" json:"permit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitPermitRequest) Reset()         { *m = WaitPermitRequest{} }
func (m *WaitPermitRequest) String() string { return proto.CompactTextString(m) }
func (*WaitPermitRequest) ProtoMessage()    {}
func (*WaitPermitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b272ab0cd84b17, []int{5}
}

func (m *WaitPermitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitPermitRequest.Unmarshal(m, b)
}
func (m *WaitPermitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitPermitRequest.Marshal(b, m, deterministic)
}
func (m *WaitPermitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitPermitRequest.Merge(m, src)
}
func (m *WaitPermitRequest) XXX_Size() int {
	return xxx_messageInfo_WaitPermitRequest.Size(m)
}
func (m *WaitPermitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitPermitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitPermitRequest proto.InternalMessageInfo

func (m *WaitPermitRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WaitPermitRequest) GetPermit() bool {
	if m != nil {
		return m.Permit
	}
	return false
}

func init() {
	proto.RegisterEnum("dev.namhyun.keyletter.VerifyStatus", VerifyStatus_name, VerifyStatus_value)
	proto.RegisterEnum("dev.namhyun.keyletter.FailedReason", FailedReason_name, FailedReason_value)
	proto.RegisterType((*Key)(nil), "dev.namhyun.keyletter.Key")
	proto.RegisterType((*Code)(nil), "dev.namhyun.keyletter.Code")
	proto.RegisterType((*GuestInfo)(nil), "dev.namhyun.keyletter.GuestInfo")
	proto.RegisterType((*VerifyRequest)(nil), "dev.namhyun.keyletter.VerifyRequest")
	proto.RegisterType((*VerifyReply)(nil), "dev.namhyun.keyletter.VerifyReply")
	proto.RegisterType((*WaitPermitRequest)(nil), "dev.namhyun.keyletter.WaitPermitRequest")
}

func init() {
	proto.RegisterFile("keyletter.proto", fileDescriptor_d6b272ab0cd84b17)
}

var fileDescriptor_d6b272ab0cd84b17 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x6d, 0x6f, 0xd2, 0x50,
	0x14, 0x5e, 0x81, 0xe1, 0x38, 0x20, 0xbb, 0x9e, 0x4c, 0x43, 0xc0, 0x98, 0xa5, 0x2e, 0x91, 0xec,
	0x43, 0x63, 0xf0, 0xe3, 0x12, 0x0d, 0xc2, 0x9d, 0xab, 0x60, 0xbb, 0xdc, 0x96, 0x2d, 0x31, 0x26,
	0x4d, 0x5d, 0x0f, 0xda, 0x8c, 0xb5, 0xd8, 0x17, 0x92, 0xfe, 0x02, 0x7f, 0x83, 0xff, 0xd6, 0xf4,
	0x52, 0x06, 0x89, 0xab, 0xfb, 0x74, 0xef, 0xb9, 0xe7, 0x79, 0xce, 0x73, 0xde, 0x2e, 0x1c, 0xde,
	0x52, 0xb6, 0xa0, 0x24, 0xa1, 0x48, 0x5b, 0x46, 0x61, 0x12, 0xe2, 0x73, 0x8f, 0x56, 0x5a, 0xe0,
	0xde, 0xfd, 0xcc, 0xd2, 0x40, 0xbb, 0x77, 0xaa, 0x3d, 0xa8, 0x4e, 0x28, 0xc3, 0x23, 0xd8, 0x5f,
	0xb9, 0x8b, 0x94, 0x3a, 0xca, 0xb1, 0xd2, 0x6f, 0x88, 0xb5, 0xa1, 0xbe, 0x84, 0xda, 0x28, 0xf4,
	0xa8, 0xc4, 0x7b, 0x06, 0x8d, 0x4f, 0x29, 0xc5, 0x89, 0x1e, 0xcc, 0x43, 0x6c, 0x43, 0x25, 0x75,
	0x0b, 0x7f, 0x25, 0x75, 0xf1, 0x15, 0x80, 0xef, 0x51, 0x90, 0xf8, 0x73, 0x9f, 0xa2, 0x4e, 0x45,
	0xbe, 0xef, 0xbc, 0xa8, 0x37, 0xf0, 0xf4, 0x8a, 0x22, 0x7f, 0x9e, 0x09, 0xfa, 0x95, 0x07, 0xc1,
	0xf7, 0xd0, 0xf8, 0xb1, 0x89, 0x26, 0xe3, 0x34, 0x07, 0xc7, 0xda, 0x83, 0x39, 0x6b, 0xf7, 0xaa,
	0x62, 0x4b, 0x41, 0x84, 0xda, 0x4d, 0xe8, 0x51, 0x21, 0x25, 0xef, 0xea, 0x1f, 0x05, 0x9a, 0x1b,
	0x95, 0xe5, 0x22, 0xc3, 0x33, 0xa8, 0xc7, 0x89, 0x9b, 0xa4, 0xb1, 0x14, 0x68, 0x0f, 0x5e, 0x97,
	0x08, 0xac, 0x39, 0x96, 0x84, 0x8a, 0x82, 0x92, 0x93, 0x23, 0x72, 0xe3, 0x30, 0x90, 0x12, 0xe5,
	0xe4, 0x73, 0xd7, 0x5f, 0x90, 0x27, 0x24, 0x54, 0x14, 0x14, 0x64, 0x50, 0xbd, 0xa5, 0xac, 0x53,
	0x95, 0xc9, 0xe5, 0x57, 0xf5, 0x03, 0x3c, 0xbb, 0x76, 0xfd, 0xe4, 0x92, 0xa2, 0x3b, 0x3f, 0xd9,
	0x34, 0x61, 0x53, 0x84, 0xb2, 0x2d, 0x02, 0x5f, 0x40, 0x7d, 0x29, 0x41, 0x52, 0xf7, 0x40, 0x14,
	0xd6, 0xe9, 0x1b, 0x68, 0xed, 0xe6, 0x89, 0x00, 0xf5, 0xf3, 0xa1, 0x3e, 0xe5, 0x63, 0xb6, 0x87,
	0x4d, 0x78, 0x62, 0xcd, 0x46, 0x23, 0x6e, 0x59, 0x4c, 0x39, 0x5d, 0x41, 0x6b, 0x37, 0x27, 0x3c,
	0x80, 0x9a, 0x61, 0x1a, 0x9c, 0xed, 0xe1, 0x21, 0x34, 0x87, 0x33, 0xfb, 0xc2, 0x29, 0x78, 0x0a,
	0x32, 0x68, 0xe9, 0x86, 0xcd, 0x85, 0x31, 0x9c, 0x3a, 0x5c, 0x08, 0x56, 0xc9, 0x21, 0x82, 0x7f,
	0xe6, 0x23, 0xdb, 0xb9, 0x30, 0x2d, 0x9b, 0x55, 0x11, 0xa1, 0x6d, 0x98, 0xd2, 0x70, 0xae, 0x87,
	0xba, 0xcd, 0xc7, 0xac, 0x86, 0x47, 0xc0, 0x04, 0xb7, 0x2e, 0x4d, 0xc3, 0xe2, 0x8e, 0xad, 0x7f,
	0xe1, 0xe6, 0xcc, 0x66, 0xfb, 0x83, 0xdf, 0x15, 0x68, 0x4c, 0x28, 0x9b, 0xca, 0xb6, 0xe0, 0x18,
	0x1a, 0x7a, 0x1c, 0xa7, 0x24, 0x17, 0xaa, 0x5b, 0xd2, 0xbb, 0x09, 0x65, 0xdd, 0x5e, 0x89, 0x4f,
	0x12, 0xaf, 0x00, 0xd6, 0x45, 0x4b, 0xeb, 0xe4, 0xbf, 0xf3, 0x2b, 0x9a, 0xda, 0x55, 0x1f, 0x41,
	0xe5, 0x9b, 0xf1, 0x0d, 0x60, 0x3b, 0x0d, 0xec, 0x97, 0x30, 0xfe, 0x19, 0x58, 0xf7, 0xd1, 0x15,
	0xed, 0x2b, 0x6f, 0x95, 0x8f, 0x27, 0xd0, 0x7b, 0x18, 0x26, 0xbf, 0xe6, 0xd7, 0x7d, 0x79, 0x7c,
	0xaf, 0xcb, 0xe3, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x8e, 0x55, 0xbe, 0xbb, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeyLetterClient is the client API for KeyLetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyLetterClient interface {
	IssueCode(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Code, error)
	VerifyCode(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyReply, error)
	WaitPermit(ctx context.Context, opts ...grpc.CallOption) (KeyLetter_WaitPermitClient, error)
}

type keyLetterClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyLetterClient(cc grpc.ClientConnInterface) KeyLetterClient {
	return &keyLetterClient{cc}
}

func (c *keyLetterClient) IssueCode(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Code, error) {
	out := new(Code)
	err := c.cc.Invoke(ctx, "/dev.namhyun.keyletter.KeyLetter/IssueCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyLetterClient) VerifyCode(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyReply, error) {
	out := new(VerifyReply)
	err := c.cc.Invoke(ctx, "/dev.namhyun.keyletter.KeyLetter/VerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyLetterClient) WaitPermit(ctx context.Context, opts ...grpc.CallOption) (KeyLetter_WaitPermitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyLetter_serviceDesc.Streams[0], "/dev.namhyun.keyletter.KeyLetter/WaitPermit", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyLetterWaitPermitClient{stream}
	return x, nil
}

type KeyLetter_WaitPermitClient interface {
	Send(*WaitPermitRequest) error
	Recv() (*GuestInfo, error)
	grpc.ClientStream
}

type keyLetterWaitPermitClient struct {
	grpc.ClientStream
}

func (x *keyLetterWaitPermitClient) Send(m *WaitPermitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keyLetterWaitPermitClient) Recv() (*GuestInfo, error) {
	m := new(GuestInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyLetterServer is the server API for KeyLetter service.
type KeyLetterServer interface {
	IssueCode(context.Context, *Key) (*Code, error)
	VerifyCode(context.Context, *VerifyRequest) (*VerifyReply, error)
	WaitPermit(KeyLetter_WaitPermitServer) error
}

// UnimplementedKeyLetterServer can be embedded to have forward compatible implementations.
type UnimplementedKeyLetterServer struct {
}

func (*UnimplementedKeyLetterServer) IssueCode(ctx context.Context, req *Key) (*Code, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCode not implemented")
}
func (*UnimplementedKeyLetterServer) VerifyCode(ctx context.Context, req *VerifyRequest) (*VerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCode not implemented")
}
func (*UnimplementedKeyLetterServer) WaitPermit(srv KeyLetter_WaitPermitServer) error {
	return status.Errorf(codes.Unimplemented, "method WaitPermit not implemented")
}

func RegisterKeyLetterServer(s *grpc.Server, srv KeyLetterServer) {
	s.RegisterService(&_KeyLetter_serviceDesc, srv)
}

func _KeyLetter_IssueCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyLetterServer).IssueCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dev.namhyun.keyletter.KeyLetter/IssueCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyLetterServer).IssueCode(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyLetter_VerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyLetterServer).VerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dev.namhyun.keyletter.KeyLetter/VerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyLetterServer).VerifyCode(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyLetter_WaitPermit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyLetterServer).WaitPermit(&keyLetterWaitPermitServer{stream})
}

type KeyLetter_WaitPermitServer interface {
	Send(*GuestInfo) error
	Recv() (*WaitPermitRequest, error)
	grpc.ServerStream
}

type keyLetterWaitPermitServer struct {
	grpc.ServerStream
}

func (x *keyLetterWaitPermitServer) Send(m *GuestInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keyLetterWaitPermitServer) Recv() (*WaitPermitRequest, error) {
	m := new(WaitPermitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KeyLetter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dev.namhyun.keyletter.KeyLetter",
	HandlerType: (*KeyLetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCode",
			Handler:    _KeyLetter_IssueCode_Handler,
		},
		{
			MethodName: "VerifyCode",
			Handler:    _KeyLetter_VerifyCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WaitPermit",
			Handler:       _KeyLetter_WaitPermit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "keyletter.proto",
}
